#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://192.168.118.129:3306/springboot_1?useUnicode=true&characterEncoding=utf8
    username: root
    password: baiyang5211314+-A
    driver-class-name: com.mysql.jdbc.Driver